import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './global.css';
import { HFlex } from '@core/components/flexes/HFlex';
import SideBar from '@lib/components/nav/SideBar';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// };

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body
				className={inter.className}
				style={{ width: '100vw', height: '100vh', minHeight: '100vh' }}
			>
				<div style={{ width: '100%', height: '100%' }}>
					<main style={{ width: '100%', height: '100%' }}>
						<Providers>
							<HFlex
								sx={{
									width: '100%',
									height: '100%',
									justifyContent: 'flex-start',
								}}
							>
								<SideBar />
								{children}
							</HFlex>
						</Providers>
					</main>
					<footer className="w-full flex items-center justify-center py-3"></footer>
				</div>
			</body>
		</html>
	);
}
