import {
  FaBookMedical,
  FaBookReader,
  FaBroom,
  FaCar,
  FaClock,
  FaCode,
  FaCoffee,
  FaGamepad,
  FaHeadphones,
  FaLanguage,
  FaPen,
  FaPeopleArrows,
  FaPhone,
  FaRegMoon,
  FaRunning,
  FaShoppingBag,
  FaThumbtack,
  FaTrashAlt,
  FaTree,
  FaTruckMoving,
  FaUmbrellaBeach,
  FaUniversity,
  FaUserGraduate,
  FaUserTie,
  FaWindowRestore,
  FaWrench,
} from "react-icons/fa";

const icons = {
  faRunning: FaRunning,
  faWindowRestore: FaWindowRestore,
  faClock: FaClock,
  faUniversity: FaUniversity,
  faThumbTack: FaThumbtack,
  faShoppingBag: FaShoppingBag,
  faPen: FaPen,
  faBookReader: FaBookReader,
  faTrashAlt: FaTrashAlt,
  faGamepad: FaGamepad,
  faPeopleArrows: FaPeopleArrows,
  faCode: FaCode,
  faRegMoon: FaRegMoon,
  faWrench: FaWrench,
  faBroom: FaBroom,
  faUserGraduate: FaUserGraduate,
  faHeadphones: FaHeadphones,
  faTree: FaTree,
  faCar: FaCar,
  faCoffee: FaCoffee,
  faBookMedical: FaBookMedical,
  faLanguage: FaLanguage,
  faPhone: FaPhone,
  faTruckMoving: FaTruckMoving,
  faUmbrellaBeach: FaUmbrellaBeach,
  faUserTie: FaUserTie,
};

export default icons;
